### ISSUE TITLE
Is boxen/brews/git still needed?

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-git#55]
Aside from the older (and insecure) version of git, it's not obvious to me what boxen's git brew provides that the standard Homebrew version does not. @mikemcquaid?

**Comment by mikemcquaid** [comment]
I don't really maintain this repo so I'm not sure but I guess it's considered to be more stable? I'm planning on getting more involved with Boxen in the next few months so I suspect I'll be unifying some of the Boxen/Homebrew brews.

**Comment by seanknox** [comment]
My bad Mike, apologies. @dgoodlad can you answer?

**Comment by toolbear** [comment]
:+1: to using homebrew's git.

Boxen on pristine install of OS X 10.10 with is borked for me (#56).

**Comment by dgoodlad** [comment]
The custom formula, as with all the custom formulae, is for stability. Having one of my core dev tools be upgraded just because homebrew decided they'd track the latest and greatest is not something I like to happen. A *great* example where this is super important is mysql; I definitely don't want to be running mysql 5.6 in dev when my production systems are on 5.1, or 5.5. There are significant changes to that software between their "minor" version bumps.

In the case of `git`, it was important at GitHub that there was a stable, predictable version. Now, it's probably debatable. I'd prefer that, for something as core as this, to make a change that allowed the *option* of using upstream's formula, but I don't think dropping support for a managed, explicitly versioned `git` is a good idea.

@toolbear let's keep discussion about #56 in #56; I understand how making this change would have avoided your specific issue, but I think it will turn into a bit of a distraction from the core discussion here.

**Comment by mikemcquaid** [comment]
I think this is basically the philosophy of Boxen's packages really. As much as I may disagree (I'm biased as a Homebrew maintainer) I can see the argument. After all, you can just use the Homebrew Boxen package instead and install Git that way if you'd rather.
